### ISSUE TITLE
main_x11.cpp is greatly outdated.

### ISSUE THREAD

**Issue by ghost** [nvpro-samples/nvpro_core#13]
Linux code for Vulkan nvpro-samples is generally outdated, but for this repo specifically `main_x11.cpp` throws a lot of compile time errors on Ubuntu 18.04.

**Comment by vivichrist** [comment]
I second this... Manjaro 18.0.2

**Comment by pixeljetstream** [comment]
we will change to glfw3 in an upcoming release that should make running on linux easier again, though getting all samples tested under linux is still a bit off.
