### ISSUE TITLE
Missing main.h

### ISSUE THREAD

**Issue by cjun714** [nvpro-samples/nvpro_core#15]
Hi, Dear team

I try to compile the code on linux, I resolved some compiling errors.
But below one I can't handle: 

``` shell
nvpwindow_internal_x11.cpp:42:10: fatal error: main.h: No such file or directory
 #include "main.h"
``` 
main.h can not be found anywhere, I think the code of this repository is incomplete.

Could you kindly fix this?
Thanks a lot!

**Comment by pixeljetstream** [comment]
linux is currently not yet supported
