### ISSUE TITLE
context_vk.cpp::vkCreateDevice takes 328 milliseconds on Ubuntu 20.04

### ISSUE THREAD

**Issue by ghost** [nvpro-samples/nvpro_core#19]
![](https://user-images.githubusercontent.com/28234322/79610414-2b528480-8101-11ea-8ca3-93eff1f649f1.png)

https://github.com/nvpro-samples/shared_sources/blob/520a374b290b53acdc8cd7953e54b15fd26278a3/nvvk/context_vk.cpp#L485

Because of this, all example programs which use nvvk have a noticeable lag each time you run them. For comparison, all OpenGL programs start instantly because no init calls take this much time there, I thought Vulkan is supposed to be faster than OpenGL, not slower? :P

**Comment by ghost** [comment]
NVIDIA Driver Version: 440.82

**Comment by procedural** [comment]
You can render 1200 frames in Crysis in 328 milliseconds. An init call should not require more work than rendering an island in 3D 1200 times.

![richard-gardner-crysis-console-05](https://user-images.githubusercontent.com/28234322/79612000-7b7f1600-8104-11ea-8d01-4f7f1eaf08e6.jpg)

**Comment by mklefrancois** [comment]
This is not an issue with nvvk, but I rather an issue with the driver and the version of Ubuntu. Many are using Ubuntu and have not reported this issue. Please try with a more recent driver.
