### ISSUE TITLE
Vulkan samples build may fail on linux because FindVulkanSDK.cmake is not FindVULKANSDK.cmake

### ISSUE THREAD

**Issue by Niko-sk2x** [nvpro-samples/nvpro_core#20]
Trying to build anything that uses vulkan may produce the following errors from cmake and then fail at link time:
```
  By not providing "FindVULKANSDK.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "VULKANSDK", but CMake did not find one.

  Could not find a package configuration file provided by "VULKANSDK" with
  any of the following names:

    VULKANSDKConfig.cmake
    vulkansdk-config.cmake

  Add the installation prefix of "VULKANSDK" to CMAKE_PREFIX_PATH or set
  "VULKANSDK_DIR" to a directory containing one of the above files.  If
  "VULKANSDK" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:41 (_add_package_VulkanSDK)
```

Because it's looking for `FindVULKANSDK.cmake` but the only file that exists is `FindVulkanSDK.cmake` which unlike on windows, is not the same file.

**Comment by NBickford-NV** [comment]
Hi Barteks2x,

Thanks - we ran into this internally with some newer versions of CMake a bit ago, so it should be fixed in a few days!

**Comment by NBickford-NV** [comment]
OK, I think this should be fixed with commit https://github.com/nvpro-samples/shared_sources/commit/ee4be91d3d6e7f2a267a37d0ada5c81f7205c571!

**Comment by NBickford-NV** [comment]
Closing, since I think this has been fixed, and it has almost been two months since the last update.
