### ISSUE TITLE
NVH fprintf segfault

### ISSUE THREAD

**Issue by seanbaxter** [nvpro-samples/nvpro_core#23]
https://github.com/nvpro-samples/shared_sources/blob/master/nvh/nvprint.cpp#L123

```cpp
fprintf(s_fd, s_strBuffer);
```

This line causes a segfault when the string has embedded % characters. This is common when Vulkan Validator pastes SPIR-V disassembly. Change to fwrite or fputs.

**Comment by mklefrancois** [comment]
Hi, thanks for reporting. Do you have a reproducer for this?

**Comment by seanbaxter** [comment]
```cpp
#include <nvh/fileoperations.hpp>

int main(int argc, const char** argv) {
  nvprintf("A string: %s\n", "It's poison %s %s %s %s.");
}
```

**Comment by NBickford-NV** [comment]
Thanks! This should be fixed now with Mathias Heyer's bulk update (https://github.com/nvpro-samples/shared_sources/blob/master/nvh/nvprint.cpp now uses fputs and checks some additional things).
