### ISSUE TITLE
raytraceKHR_vk.cpp instances buffer validation error 

### ISSUE THREAD

**Issue by Jebbly** [nvpro-samples/nvpro_core#27]
When building [vk_mini_path_tracer](https://github.com/nvpro-samples/vk_mini_path_tracer), the following validation layer error is output during runtime:

```
ERROR: VUID-vkCmdBuildAccelerationStructuresKHR-geometry-03673
 --> Validation Error: [ VUID-vkCmdBuildAccelerationStructuresKHR-geometry-03673 ] Object 0: handle = 0x10d1641d488, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0xd175b40000000013, name = nvvk::RaytracingBuilderKHR::m_instBuffer.buffer ( in raytraceKHR_vk.cpp:262), type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x8a7de95d | vkCmdBuildAccelerationStructuresKHR(): The buffer associated with pInfos[0].pGeometries[0].geometry.instances.data was not created with VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR. The Vulkan spec states: The buffers from which the buffer device addresses for all of the geometry.triangles.vertexData, geometry.triangles.indexData, geometry.triangles.transformData, geometry.aabbs.data, and geometry.instances.data members of all pInfos[i].pGeometries and pInfos[i].ppGeometries are queried must have been created with the VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR usage flag
 ```
 
 I was able to resolve this error by changing line 261 of raytraceKHR_vk.cpp to this:
 ```  m_instBuffer = m_alloc->createBuffer(cmdBuf, geometryInstances, VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT | VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR);```
but I do not have much experience with Vulkan so I'm not sure if this is the ideal/correct solution.

**Comment by Jebbly** [comment]
If that solution is fine, I would be happy to create a related pull request for this issue!

**Comment by NBickford-NV** [comment]
Hi Jeffrey - thanks for the quick report! It looks like Martin-Karl fixed this a few hours ago with commit 81b3271, but this also turned up an issue with the TLAS scratch buffer usage flags that only appears when using the latest main branch of the Vulkan Validation Layers. I've just made a commit to fix this in the upstream repository, and I'll close this issue when that's merged into the public repository.

Thanks again!

**Comment by NBickford-NV** [comment]
Okay - the fixed TLAS scratch buffer usage flags have been fixed in the latest bulk update - see https://github.com/nvpro-samples/nvpro_core/commit/fd6f14c4ddcb6b2ec1e79462d372b32f3838b016#diff-1481edec8577c4d7009c08b60447a6e183e0639022beb5019a5eaa1f40476d12R354 .

Thanks again!

**Comment by Jebbly** [comment]
That's great to hear - thank you for the quick response and update!
