### ISSUE TITLE
perproject_globals.hpp doesn't exist?

### ISSUE THREAD

**Issue by missmah** [nvpro-samples/nvpro_core#28]
![image](https://user-images.githubusercontent.com/10825214/131194928-13f7da27-4a79-4a0d-b696-6b3ac46258c8.png)

https://github.com/nvpro-samples/nvpro_core/search?q=globals

I'm running into a failure to include that file, but I can't find it in the repository, or mentioned anywhere in the cmake build scripts.

Thanks!

**Comment by nvmheyer** [comment]
Hi, thanks for reporting!
This was an update going awry.
I uploaded an update to nvpro_core that should fix these issues.

Edit: commit fd6f14c4ddcb6b2ec1e79462d372b32f3838b016 is the fix
