### ISSUE TITLE
{'glewGetErrorString', 'glewGetString', 'glewInit', 'glewIsSupported'} redefinition, different type modifiers

### ISSUE THREAD

**Issue by cmei** [nvpro-samples/nvpro_core#3]
Hello,

I'm getting the four errors:
{'glewGetErrorString', 'glewGetString', 'glewInit', 'glewIsSupported'} redefinition; different type modifiers

when I build the project in VS 2015 (CMake did not spit out any errors).

Is this a known issue?

**Comment by pixeljetstream** [comment]
glew has been replaced
