### ISSUE TITLE
Error occurs when creating host-visible image

### ISSUE THREAD

**Issue by bacTlink** [nvpro-samples/nvpro_core#31]
I call the ```ResourceAllocator::createImage``` with ```VkMemoryPropertyFlags memProps = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT``` and encounter an error in ```fillBakedAllocateInfo``` when allocating memory in ```memallocator_vk.cpp```. The function ```getMemoryType()``` fails to fetch a valid memory type.
I debugged for a while but still can't fix this.

How to correctly create a host-visible image? My codes:
```
  VkExtent2D size{ width, height };
  auto colorCreateInfo = nvvk::makeImage2DCreateInfo(size, VK_FORMAT_R16G16B16A16_SFLOAT,
			VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_STORAGE_BIT, true);
  nvvk::Image image = m_pAlloc->createImage(colorCreateInfo, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT); // <-- error occurs
```

**Comment by mklefrancois** [comment]
Hi, to create images with host visible property, the image has to be created with tiling linear. It is not possible to have a host visible version of an optimized tiling image. 

The following code will work.
```
  VkExtent2D size{ width, height };
  auto       colorCreateInfo = nvvk::makeImage2DCreateInfo(size, VK_FORMAT_R16G16B16A16_SFLOAT,
                                                     VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT, false);
  colorCreateInfo.tiling     = VK_IMAGE_TILING_LINEAR;
  nvvk::Image image = m_alloc.createImage(colorCreateInfo, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT);
```

Note, linear images has many limitations, they cannot have mip-mapping, no sampling and many more. Only usage transfer src and dst are accepted.

If the goal is to access the image buffer as a normal buffer, you need to copy the image to a buffer using [`vkCmdCopyImageToBuffer`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdCopyImageToBuffer.html) and [`vkCmdCopyBufferToImage`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdCopyBufferToImage.html) to copy the modified buffer back to an image. 

The allocator has a convenient method to create images from data. The data is correctly transferred using staging buffer.
See:
```
Image ResourceAllocator::createImage(const VkCommandBuffer&   cmdBuf,
                                     size_t                   size_,
                                     const void*              data_,
                                     const VkImageCreateInfo& info_,
                                     const VkImageLayout&     layout_)
```
