### ISSUE TITLE
GltfScene::computeSceneDimensions()

### ISSUE THREAD

**Issue by bacTlink** [nvpro-samples/nvpro_core#32]
In [gltfscene.cpp](https://github.com/nvpro-samples/nvpro_core/blob/master/nvh/gltfscene.cpp#L677), when calculating the bounding box, ```valMin``` is updated using ```locMin```. However, ```locMin``` is not necessary the minimum after applying the ```worldMatrix```. ```valMin``` should be updated using both ```locMin``` and ```locMax```. ```valMax``` has the same problem.

**Comment by mklefrancois** [comment]
Thanks for spotting this, a fix is coming shortly.

**Comment by NBickford-NV** [comment]
Looks like Martin-Karl fixed this in https://github.com/nvpro-samples/nvpro_core/commit/ec454643a46d7d036724001ac3e453ea47787b70 - thanks again for the issue report!
