### ISSUE TITLE
For what cadscenefile.h used for?

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/nvpro_core#39]
Hello.
I read code of this file and I see cadscenefile.h not used for vk_raytracer, for example.
And I see with this header file I can read gz file and gltf with cgltf, not tinygltf.
One more question is which file format in gz file?
Thank you

**Comment by mklefrancois** [comment]
Hi, the `.gz` is in fact `.csf.gz`. The `.csf`, for CAD scene format is an internal format representing what can be used by CAD software and the `.gz` is the compressed version of it.
