### ISSUE TITLE
Undefined refrences

### ISSUE THREAD

**Issue by sivansh11** [nvpro-samples/nvpro_core#44]
I am trying out https://nvpro-samples.github.io/vk_mini_path_tracer/index.html
I am getting undefined refrences
```
[build] /usr/bin/ld: CMakeFiles/tut1.dir/main.cpp.o: in function `nvvk::Context::Context()':
[build] /home/sivansh/programming/c++/trying_nvvk/apps/tut1/../../deps/nvpro_core/nvvk/context_vk.hpp:290: undefined reference to `nvvk::GpuCrashTracker::GpuCrashTracker()'
[build] /usr/bin/ld: CMakeFiles/tut1.dir/main.cpp.o: in function `nvvk::Context::~Context()':
[build] /home/sivansh/programming/c++/trying_nvvk/apps/tut1/../../deps/nvpro_core/nvvk/context_vk.hpp:284: undefined reference to `nvvk::GpuCrashTracker::~GpuCrashTracker()'
[build] /usr/bin/ld: ../../../deps/bin_x64/Debug/libnvpro_core_vk.a(context_vk.cpp.o): in function `nvvk::Context::initInstance(nvvk::ContextCreateInfo const&)':
[build] /home/sivansh/programming/c++/trying_nvvk/deps/nvpro_core/nvvk/context_vk.cpp:220: undefined reference to `isAftermathAvailable()'
[build] /usr/bin/ld: /home/sivansh/programming/c++/trying_nvvk/deps/nvpro_core/nvvk/context_vk.cpp:222: undefined reference to `nvvk::GpuCrashTracker::initialize()'
[build] /usr/bin/ld: ../../../deps/bin_x64/Debug/libnvpro_core_vk.a(context_vk.cpp.o): in function `nvvk::Context::initDevice(unsigned int, nvvk::ContextCreateInfo const&)':
[build] /home/sivansh/programming/c++/trying_nvvk/deps/nvpro_core/nvvk/context_vk.cpp:654: undefined reference to `isAftermathAvailable()'
[build] /usr/bin/ld: ../../../deps/bin_x64/Debug/libnvpro_core_vk.a(context_vk.cpp.o): in function `nvvk::ContextCreateInfo::ContextCreateInfo(bool, unsigned int)':
[build] /home/sivansh/programming/c++/trying_nvvk/deps/nvpro_core/nvvk/context_vk.cpp:794: undefined reference to `isAftermathAvailable()'```

#if defined(NVVK_SUPPORTS_AFTERMATH) && defined(NVP_SUPPORTS_VULKANSDK)
is never defined on my system ?

**Comment by NBickford-NV** [comment]
Hi Sivansh! I'm trying to reproduce this, but haven't succeeded in getting this error yet. I see you're using a custom `trying_nvvk` solution here; my best guess is, when you add the executable, like this:

```
#####################################################################################
# Executable
#
add_executable(${PROJNAME} ${SOURCE_FILES} ${COMMON_SOURCE_FILES} ${GLSL_SOURCES})
```

is it possible the CMakeLists.txt file for `trying_nvvk/apps/tut1` is missing `${COMMON_SOURCE_FILES}`? If you happen to have a copy of the `trying_nvvk/apps` repository, I can try building it as well.

In particular, `${COMMON_SOURCE_FILES}` [was added to this line in March](https://github.com/nvpro-samples/vk_mini_path_tracer/commit/f29c5b9d5146259ba0fc8e5840736c249bec340f), so if `trying_nvvk/apps/tut1` was copied from `vk_mini_path_tracer` before then, that could cause this issue when building with a new version of nvpro_core!

The missing implementations of `nvvk::GpuCrashTracker::GpuCrashTracker()` and `isAftermathAvailable()` should be in `nvpro_core/nvvk/nsight_aftermath_vk.cpp` and `nvpro_core/nvp/perproject_globals.cpp`. These should be included in the `COMMON_SOURCE_FILES` variable as follows:

* https://github.com/nvpro-samples/vk_mini_path_tracer/blob/main/CMakeLists.txt#L29 calls `_add_nvpro_core_lib()`:
  * `_add_nvpro_core_lib()` in `nvpro_core/setup.cmake` calls `_process_shared_cmake_code()`: https://github.com/nvpro-samples/nvpro_core/blob/8096be945319118ab8ca8ce873d1ee46c387e8ac/cmake/setup.cmake#L1041
    * `_process_shared_cmake_code()` adds `perproject_globals.cpp` to `COMMON_SOURCE_FILES`: https://github.com/nvpro-samples/nvpro_core/blob/8096be945319118ab8ca8ce873d1ee46c387e8ac/cmake/setup.cmake#L993
  * `_add_nvpro_core_lib()` calls `_add_package_NsightAftermath()`: https://github.com/nvpro-samples/nvpro_core/blob/8096be945319118ab8ca8ce873d1ee46c387e8ac/cmake/setup.cmake#L1045
    * `_add_package_NsightAftermath()` adds `nsight_aftermath_vk.cpp` (even if the system doesn't have Nsight Aftermath, this is OK): https://github.com/nvpro-samples/nvpro_core/blob/8096be945319118ab8ca8ce873d1ee46c387e8ac/cmake/setup.cmake#L644
* Each `vk_mini_path_tracer` subproject calls `add_executable()` with `COMMON_SOURCE_FILES` listed: https://github.com/nvpro-samples/vk_mini_path_tracer/blob/f29c5b9d5146259ba0fc8e5840736c249bec340f/_edit/CMakeLists.txt#L64

Hope this helps - thanks for the issue!
