### ISSUE TITLE
add new simple sample showing usage of NV Vk exts for RTX IO functionality (like new DirectStorage 1.1 new Gdeflate)

### ISSUE THREAD

**Issue by oscarbg** [nvpro-samples/nvpro_core#46]
Would be nice to have new vk samples showing usage of new recent nv vk exts like:
*Rtx io vk exts..
*Ada SER vk ext..
*Ada OMM vk ext..
*Ada DMM (still no vk ext)
Don’t know if correct place to ask..
Thanks..

**Comment by NBickford-NV** [comment]
Hi @oscarbg ! We added the new [vk_memory_decompression](https://github.com/nvpro-samples/vk_memory_decompression) sample in March. Additionally, we have small samples for Shader Execution Reordering, OMMs, and DMMs in https://github.com/nvpro-samples/vk_mini_samples/tree/main/samples.

Thank you!
