### ISSUE TITLE
Error occured when compiling with mingw64 gcc on windows

### ISSUE THREAD

**Issue by WangZhiCheng2001** [nvpro-samples/nvpro_core#55]
I'm trying to compile this project on windows with mingw64 gcc (via msys2). I had added some windows version definitions to confirm that the compiler gets correct windows API version. However I still got error when compiling:
```
[build] [ 28%] Building CXX object nvpro_core/CMakeFiles/nvpro_core.dir/nvp/nvpsystem_win32.cpp.obj
[build] F:\xxx\3rdparty\nvpro_core\nvp\nvpsystem_win32.cpp:52:10: error: expected constructor, destructor, or type conversion before '(' token
[build]    52 | _declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001;
[build]       |          ^
[build] mingw32-make[3]: *** [nvpro_core\CMakeFiles\nvpro_core.dir\build.make:567: nvpro_core/CMakeFiles/nvpro_core.dir/nvp/nvpsystem_win32.cpp.obj] Error 1
```
It seems that there should be `__declspec(dllexport)` instead of `_declspec(dllexport)`. After replacing it, the project can be compiled. Am I doing correctly?

**Comment by tigrazone** [comment]
for successful compile with MinGW please use these changes:
1. add after 
https://github.com/nvpro-samples/nvpro_core/blob/e15f6038b54c39b4ad756c9e14a8354b56b4d82f/nvp/nvpfilesystem.cpp#L25
```
#ifndef _MSC_VER
#undef _WIN32
#endif
```

2. change 
https://github.com/nvpro-samples/nvpro_core/blob/e15f6038b54c39b4ad756c9e14a8354b56b4d82f/nvp/nvpsystem_win32.cpp#L51
https://github.com/nvpro-samples/nvpro_core/blob/e15f6038b54c39b4ad756c9e14a8354b56b4d82f/nvp/nvpsystem_win32.cpp#L52
https://github.com/nvpro-samples/nvpro_core/blob/e15f6038b54c39b4ad756c9e14a8354b56b4d82f/nvp/nvpsystem_win32.cpp#L53
to
```
extern "C" {
#ifdef _MSC_VER
_declspec(dllexport)
#else
__attribute__((dllexport))
#endif
DWORD NvOptimusEnablement = 0x00000001;
}
```

**Comment by WangZhiCheng2001** [comment]
It works. Thanks a lot!
