### ISSUE TITLE
how HdrEnvDome used?

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/nvpro_core#59]
Hello!
In source code of https://github.com/nvpro-samples/vk_shaded_gltfscene I see is HdrEnvDome used.
I have 2 questions.
1. Please explain how it works and used for vk_shaded_gltfscene.
2. Is I understand well it is used in raster renderer - baked GGX info. Can this info can be used in raytrace renderer?
Thank you

**Comment by mklefrancois** [comment]
Hi, the HdrDomeEnv is used by the raster renderer. 
It has two main purposes:
1. Draw the HDR in the background. The scene is draw on top of it.
2. Provide the diffuse and specular contribution used by the lighting equation in the fragment shader, which simulates the light contribution from the HDR and the reflection.
