### ISSUE TITLE
Invalid string concatination in main.h

### ISSUE THREAD

**Issue by Delwin9999** [nvpro-samples/nvpro_core#6]
shared_sources/main.h:92:63: error: unable to find string literal operator ‘operator""**VA_ARGS**’ with ‘const char [90]’, ‘long unsigned int’ arguments
 #   define  LOGE(...)  { nvprintfLevel(2, **FILE**"("S__LINE__"): **ERROR**:\n"**VA_ARGS**); }
                                                               ^
Solution is to put spaces in.

**Comment by pixeljetstream** [comment]
fixed
