### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/nvpro_core#61]
https://github.com/nvpro-samples/nvpro_core/blob/a90c640052855ef4734d3b088b901d2c9680d9b9/nvvkhl/shaders/bsdf_functions.h#L514

I think correct way of this calculation is
`float G12 = ggx_smith_shadow_mask(G1, G2, k10, vec3(dot(data.k2, mat.T), dot(data.k2, mat.B), nk2), mat.roughness); `

**Comment by mklefrancois** [comment]
Thank you for reporting this, this actually looks like a typo.

**Comment by mklefrancois** [comment]
Closing with 61883f7
