### ISSUE TITLE
issue when I load glb file and try to save as gltf

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/nvpro_core#65]
I open glb file and try to save with vk_gltf_renderer to gltf file to other folder.
Program fails and file not saved.
Under debugger I see uri_decoded is ""
fs::create_directories(dstFile.parent_path()); from line 133 doesnt create directory
Program fails on line 135 if(fs::copy_file(srcFile, dstFile, fs::copy_options::update_existing))
![image](https://github.com/user-attachments/assets/e0b48f20-f4f4-4053-b395-d960dd31777a)

**Comment by mklefrancois** [comment]
Thanks, this specific issue has been fixed. Looking into supporting `.glb` saving too.

**Comment by tigrazone** [comment]
I opened [draco compressed glb](https://github.com/gameknife/gkNextRenderer/blob/main/assets/models/kitchen.glb) and resave it to kitchen.glb
Saved as gltf file with 841 bin files
Strange but thank you ;-)
Result is [here](https://drive.google.com/file/d/1FHS-Qp3Rgpx9RnDWXMDJEFBKDJgeTHha/view?usp=drive_link)

**Comment by mklefrancois** [comment]
`KHR_draco_mesh_compression` is not a supported feature at the moment. 
See: https://github.com/nvpro-samples/vk_gltf_renderer?tab=readme-ov-file#gltf-extensions

**Comment by tigrazone** [comment]
I added draco by myself for load scenes only

**Comment by mklefrancois** [comment]
I've added Draco as well and I can see the weird behavior, but this is how tinygltf deals with it. Loading kitchen.glb (Draco compressed: 5600KB), save to .glb (uncompressed: 22200KB) , reload that .glb and save it back end up with 1681 .bin files! 

Since loading back the glTF scene works, I guess it is more an unexpected behavior from tinygltf. Maybe you could file an issue over there.

**Comment by tigrazone** [comment]
And some bins are small - maybe empty images

**Comment by tigrazone** [comment]
[Here](https://github.com/gameknife/gkNextRenderer/tree/main/assets/models) is some draco compressed glbs. I communicated with author and he is export these glbs by blender
