### ISSUE TITLE
anisotropy disc test rendered wrong

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/nvpro_core#67]
rendered by vk_gltf_renderer
![aniso-issue](https://github.com/user-attachments/assets/e73aeab4-fe36-43ae-a040-72cc96fb798f)

reference
![screenshot_Large](https://github.com/user-attachments/assets/fee7cd9d-bd5e-4d43-8860-0b5e226ed602)

scene from [KhronosGroup/glTF-Sample-Assets/Models/AnisotropyDiscTest]( https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/AnisotropyDiscTest)

as we see, upper disks not rendered well. Bright spots not on same positions.

**Comment by mklefrancois** [comment]
The top row is visible, but it depends on lighting and viewing angle.
![image](https://github.com/user-attachments/assets/107c81d5-18d8-4f67-92c9-2736cad0d66b)

The roughness is correctly modified in X and Y, as we can see here:
![image](https://github.com/user-attachments/assets/3574837d-18a3-4c04-be0d-24d000c8aebe)

I couldn't find any problems according to the specifications. I am not sure if the reference image is actually correct.
