### ISSUE TITLE
Specular/Gloss textures

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/nvpro_core#69]
why renderer doesnt support Specular/Gloss textures?
is it possible to implement it?

**Comment by mklefrancois** [comment]
This was deprecated, see the archived extensions:
https://github.com/KhronosGroup/glTF/blob/main/extensions/README.md#archived-extensions

**Comment by tigrazone** [comment]
is it really to convert this crenes to metallic/ roughness?

**Comment by mklefrancois** [comment]
The extension [KHR_materials_pbrSpecularGlossiness](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Archived/KHR_materials_pbrSpecularGlossiness/README.md) will be finally supported.

**Comment by tigrazone** [comment]
but not rendered well by vk_gltf_renderer. 
can it be fixed?

**Comment by tigrazone** [comment]
![specgloss](https://github.com/user-attachments/assets/ae6fd735-bc5f-4bae-8891-ae24a014c1ee)
I try to open [SpecGlossVsMetalRough test scene](https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/SpecGlossVsMetalRough)

**Comment by mklefrancois** [comment]
Can you please try again. The projects were updated today. 
You should now see:
![image](https://github.com/user-attachments/assets/31cec72b-1766-4ee2-863d-09791618d0a3)

**Comment by tigrazone** [comment]
everything is ok now. thank you!
