### ISSUE TITLE
feature request: area lights

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/nvpro_core#70]
I have a [scene with 3 area lights](https://drive.google.com/file/d/1PBPEVCyIiyXfBoKkBplTq-sToelfms2s/view?usp=sharing) and I think area lights brightness not added to radiance/throughput because rendered image looks overbrighted.
Scene is closed in box and HDRI/sky&sun dont affected
![bmp-official](https://github.com/user-attachments/assets/ff9c34ca-1ece-4857-be49-d641f95c9318)

**Comment by mklefrancois** [comment]
It looks as if the firefly filter is clipping the light. 
This can be corrected by changing the Max Luminance. 
There is no function to evaluate what the maximum incoming light might be, but there is a one-time calculation when switching between HDR and Physical Sun & Sky, but nothing goes through the evaluation of emissive objects. This is left to the user.

![image](https://github.com/user-attachments/assets/350d4eec-a209-4b0e-b513-be8b1f86b197)

And here is with some Tonemapper adjustments

![image](https://github.com/user-attachments/assets/f2fae114-8c53-4d18-914b-70ea817846f6)

**Comment by tigrazone** [comment]
what about processing of emissive objects and convert it to area lights to do more processing in sampleLights() for NEE?
is it planned to implement?

**Comment by mklefrancois** [comment]
There is a proposal for [KHR_lights_area](https://github.com/KhronosGroup/glTF/issues/1940), and we have some code for the basic area light type, but until this feature is ratified by the Khronos group, we don't plan to add custom support for area lights.
