### ISSUE TITLE
overbrights

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/nvpro_core#71]
I have a [scene](https://drive.google.com/file/d/1vnBy3xDVjOaeAVANaPAfRsfQnlmHAfgL/view?usp=sharing) which rendered overbright.
Is it posible to autoexposure or use all lights power for automatically balance of lights in scene.
In sky mode all looks ok
![image](https://github.com/user-attachments/assets/98b20aed-2da5-49a2-909d-3d7bd275ab4f)

But when I upload HDRI and also when I set intensity to 0 - I have overbright
![image](https://github.com/user-attachments/assets/78bbba19-43df-4393-a355-c98dc62db81d)

Looks like an issue

**Comment by tigrazone** [comment]
one more case of this issue - sun disk scale = 0 or sun disk intensity = 0 make overbrights
![image](https://github.com/user-attachments/assets/9c119440-dc2e-4a1b-b8d3-bc914ef33244)

![image](https://github.com/user-attachments/assets/a417d377-61e2-45c3-a265-069b4b45e6d2)

**Comment by tigrazone** [comment]
one more [scene with emissive textures](https://drive.google.com/file/d/1g81gsw1kG4vAPae82xWKoXm4IESypKb9/view?usp=sharing)
with HDRI on
![emiss1](https://github.com/user-attachments/assets/db23b352-da45-475a-aace-972db170dea8)

HDRI off
![emiss-no-hdri2](https://github.com/user-attachments/assets/7f5b2445-c8db-4d50-9aeb-403689fd84f7)

**Comment by mklefrancois** [comment]
Have you tried the tonemappers ?

**Comment by tigrazone** [comment]
tone mappers doesnt helps.
emissive area lights not calculated in MIS well.
in code processed hdris and punctual lights, not area lights

**Comment by mklefrancois** [comment]
The scene has indeed very strong lights, which I believe doesn't follow the rule of the [`intensity`](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_lights_punctual/README.md#light-shared-properties) parameter, which is lumens per steradian (lm/sr).

There are a few things which can be done:
- Increase "Max Luminance", which is controlling the Firefly Filter and is cutting out incoming energy.
- Reduce the Tonemapper exposure to compensate the over bright lights
- Set the sun elevation to -90 deg, to remove any contribution from the Physical Sun & Sky model. Changing the Disk Scale is not physically correct, but a user control was added for "artistical effect", but only the 1.0 value is correct. 

![image](https://github.com/user-attachments/assets/9ef53a30-b307-4fcd-a3dd-b49fe39c3d1d)

Same is true for the SciFi scene 

![scifi](https://github.com/user-attachments/assets/4dc900a8-fcd4-4a44-a297-e4396c7f8b9d)

**Comment by tigrazone** [comment]
big versions of images doesnt open (started from [private-user-images.githubusercontent.com](https://private-user-images.githubusercontent.com/)

**Comment by tigrazone** [comment]
thank you for explaination. is this parameters can be automatic processed?
for example, "auto exposure" which can measure max luminance and fit parameters?

**Comment by mklefrancois** [comment]
An auto-exposure can be done, but to properly do this, we need the inverse of the tonemapper in use. We do not plan this feature in the short term.
