### ISSUE TITLE
how to use compress.glsl for tangent, normal compaction?

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/nvpro_core#78]
I try to use [compress.glsl](https://github.com/nvpro-samples/vk_raytrace/blob/master/shaders/compress.glsl) from vk_raytrace project for compress normals, tangents but when I put compressed to GPU(just remake like done with vertex color, change types of tangents, normal to uint on shader), program hands up and computer hangs up also.
Also texture coords can be compressed by packFloat2x16() and unpacked by unpackFloat2x16().
tangent.w can be stored as sign of texture coord x, for example

i.e.
https://github.com/nvpro-samples/nvpro_core/blob/5131ae559478ab333a18801c2ccf3e5a513ddc9a/nvvkhl/shaders/vertex_accessor.h#L40-L43
can be rewriten as
```
 layout(buffer_reference, scalar) readonly buffer VertexNormal       { uint _[]; }; 
 layout(buffer_reference, scalar) readonly buffer VertexTexCoord0    { uint _[]; }; 
 layout(buffer_reference, scalar) readonly buffer VertexTexCoord1    { uint _[]; }; 
 layout(buffer_reference, scalar) readonly buffer VertexTangent      { uint _[]; }; 
```

with this technique we can use 4 dwords vs 11 dwords for this fields

**Comment by NBickford-NV** [comment]
Hi @tigrazone ! My initial thought is that you might be accessing past the end of one of your buffers. Have you tried using [Nsight Aftermath](https://github.com/nvpro-samples/vk_mini_samples/tree/main/samples/crash_aftermath) to get a crash diagnostic? Since vk_raytrace works, this sounds like an application bug; if there's a repro case I can run, I can dig in deeper. Thank you!

**Comment by tigrazone** [comment]
> Have you tried using [Nsight Aftermath](https://github.com/nvpro-samples/vk_mini_samples/tree/main/samples/crash_aftermath) to get a crash diagnostic?

I dont understand how to use it with vk_gltf_renderer.
I try to look for `nvvk::ContextCreateInfo` in nvpro_core code and vk_gltf_renderer code - not used. only in comments.
Instruction from [crash_aftermath](https://github.com/nvpro-samples/vk_mini_samples/tree/main/samples/crash_aftermath) doesnt help me.
I done Setup step from instruction but how to integrate I dont understand. 
Can you help me?

**Comment by mklefrancois** [comment]
Can you try with this patch (vk_gltf_renderer)?

[aftermath.patch](https://github.com/user-attachments/files/18008412/aftermath.patch)

Make sure the Aftermath SDK path is set in CMake (NSIGHT_AFTERMATH_SDK)

This should generate a dump, most probably next to the opened file.

**Comment by tigrazone** [comment]
I use [aftermath.patch](https://github.com/user-attachments/files/18008412/aftermath.patch), recompile and run.
I do my work on [fork, pack branch](https://github.com/tigrazone/nvpro_core/tree/pack).
It contains 3 commits with steps to implement my pack tasks.
2 steps ok  but step 3 make program fail.
Program closed before aftermath write something to dump file.
![33](https://github.com/user-attachments/assets/09ff6086-86bf-477e-8800-a29a02e6c7c2)

Can you do code review of my code on step 3, last commit?
Please help to solve this problem

**Comment by mklefrancois** [comment]
Just briefly looking at it, but it doesn't seem to handle handedness properly. It is the bitangent that should be inverted, not the tangent. But the crash is somewhere else, but related. If you were looking at vk_raytrace, I was encoding the value in the less significant bit of `texcoord.y` . Maybe encode it in a ivec2?

**Comment by tigrazone** [comment]
I pack 2 floats to uint by
https://github.com/tigrazone/nvpro_core/blob/3784c14bafcc53ca64e3ddce214c2028b8aa9d64/nvvkhl/shaders/vertex_accessor.h#L106-L107
And I use store of tangent.w sign in texcoord.x
https://github.com/tigrazone/nvpro_core/blob/3784c14bafcc53ca64e3ddce214c2028b8aa9d64/nvvkhl/shaders/vertex_accessor.h#L158-L161

**Comment by tigrazone** [comment]
I [pack tangent in different way now](https://github.com/tigrazone/nvpro_core/commit/8ceb48dafbe1f4924501743829ebdd81775e8466).
Works ok. 
task is done

**Comment by mklefrancois** [comment]
I'm curious, have you measured any performance gain? 
Can you share any metrics?

**Comment by tigrazone** [comment]
I dont have metrics and measurement appications.
fps almost is same. please check by yourselfs.
I changed pack/unpack tangent code a lot.
please use last commit from my fork, branch alternative-tangent-pack
